preguntasLenguaje = ['1.¿Qué clase de sujeto tiene la oración: María escribe?',
'2.¿A qué período pertenece Rafael Alberti?', 
'3.¿A qué movimiento pertenece literario Fernando de Rojas?', 
'4.¿Cuál de las siguientes palabras tiene un hiato?', 
'5.¿A qué período pertenece Garcilaso de la Vega?',
'6.¿Cómo continúa el siguiente refrán: "Nunca es tarde..."?', 
'7.¿Quién escribió "Fuenteovejuna"?', 
'8.¿A qué movimiento literario pertenece Emilia Pardo Bazán?', 
'9.¿Cuál es la onomatopeya del pájaro?',
'10.¿Cuál de las siguientes palabras debería de llevar tilde según las reglas ortográficas?', 
'11.¿Cuál de las siguientes palabras no pertenece a la familia de las otras tres?',
'12.¿A qué período pertenece Montesquieu?',
'13.El libro de la Selva es una obra de:', 
'14.¿A qué período pertenece Benjamin Franklin?', 
'15.¿Cómo se denomina el intercambio de ideas y opiniones alternas entre dos o más personas?',
'16.¿A qué período pertenece Voltaire?', 
'17.¿A qué movimiento literario pertenece Valle-Inclán?', 
'18.¿Cómo continúa el siguiente refrán: "Quien dice la verdad..."?',
'19.¿Cuál de las siguientes palabras no se encuentra escrita correctamente?', 
'20.El siguiente autor no pertenece al Realismo o Naturalismo del siglo XIX',
'21.¿Quién escribió "Hansel y Gretel"?', 
'22.¿Quién escribió "Peter Pan"?',
'23.¿Cuál de las siguientes palabras tiene un diptongo?',
'24.¿Cuál de las siguientes palabras es un sustantivo?',
'25."Banquete de Boda" es una obra escrita por:',
'26.¿Quién escribió: 100 años de Soledad?', 
'27.Una palabra compuesta:',
'28.¿Cuál es la primera persona del singular del condicional simple de indicativo del verbo estudiar?',
'29.¿Cómo se denomina el intercambio de ideas y opiniones alternas entre dos o más personas?',
'30.¿Cuál de las siguientes corresponde con el significado de "emanar"?', 
'31.¿A qué período pertenece Federico García Lorca?',
'32.¿Quién es la autora de "Harry Potter"?',
'33.¿Qué expresa el modo subjuntivo del verbo?', 
'34.¿A qué movimiento literario pertenece José de Espronceda?']

respuestasLenguaje = ['Sujeto agente',
'Generación del 27',
'Renacimiento',
'Biografía',
'Siglo de Oro',
'Si la dicha es buena',
'Lope de Vega',
'Naturalismo',
'Pío',
'Crater',
'Animal',
'Siglo de las Luces',
'Rudyard Kipling',
'Siglo de las Luces',
'Diálogo',
'Siglo de las Luces',
'Modernismo',
'Ni peca ni miente',
'Jerminar',
'Garcilaso de la Vega',
'Los hermanos Grimm',
'James Matthew Barrie',
'Luego',
'Manjar',
'Emilia Pardo Bazán',
'Gabriel García Márquez',
'Abrecartas',
'Estudiaría',
'Diálogo',
'Desprender',
'Generación del 27',
'Rowling',
'Deseo',
'Romanticismo']